server {
    listen 80;
    server_name gymplat.com www.gymplat.com;

    location / {
        proxy_pass http://gymplat-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # SSL Configuration (Uncomment and provide paths)
    # listen 443 ssl;
    # ssl_certificate /etc/nginx/certs/gymplat.crt;
    # ssl_certificate_key /etc/nginx/certs/gymplat.key;
    
    # CORS
    add_header Access-Control-Allow-Origin *;
}
